### ISSUE TITLE
Web Release mode flickery

### ISSUE THREAD

**Issue by sdegenaar** [Knightro63/three_js#119]
I have a globe that works perfectly, but in release mode with latest version it is all very flickery. Fine on desktop. If I go back to three_js: ^0.1.7 it works in release mode. On latest version of flutter as well 3.38.1.

Thanks in advance

**Comment by Knightro63** [comment]
Hi @sdegenaar,

I believe this has been fixed in the newest update. It had to do with flutter_angle making debug calls without being in debug mode.

**Comment by sdegenaar** [comment]
Thanks @Knightro63 However, I'm still experiencing the flickering issue with `three_js: ^0.2.7` (which appears to be the latest version on pub.dev).

Environment:
  - Flutter: 3.38.1
  - three_js: 0.2.7
  - Platform: Web (release mode only - debug mode works perfectly)
  - Renderer: Both CanvasKit and HTML renderer show flickering

What's happening:
  When using `Line` geometry alongside `InstancedMesh` (for globe surface dots), the rendering starts correctly but then           becomes flickery within a few frames. The "flickering" appears as vertical lines across the InstancedMesh geometry.

What works:
  - Debug mode on web - perfect
  - Desktop (macOS) - perfect  
  - three_js 0.1.7 in release mode - perfect (but has label performance issues)
  - Release mode WITHOUT Line geometry - perfect

Workaround:
  Currently using InstancedMesh spheres instead of Line geometry, which works but loses the visual quality of shader-based lines.

Thanks for your help!

**Comment by Knightro63** [comment]
Hi @sdegenaar,

I made some changes and a new package. If you want to use the old renderer you can now use three_js_webgl: ^0.0.1. This will give you the renderer that was used in version 0.1.7 with all the newest updates. 

There must be an issue with how the instance meshes are handled in the 0.2.0+ renderer. I will try to look into it but i would need an example to help.
