### ISSUE TITLE
Can't show keyboard on android

### ISSUE THREAD

**Issue by Mamena2020** [Knightro63/three_js#37]
Hi, I have a problem using this TextField on android. The TextField cannot display the keyboard on android when using this plugin. any solution?

```
D/InputMethodManager(10040): showSoftInput() view=io.flutter.embedding.android.FlutterView{c8759f6 VFE...... .F...... 0,0-1280,739 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
I/ImeTracker(10040): com.example.myapp:a6c9e7fa: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
D/InsetsController(10040): show(ime(), fromIme=true)
W/RemoteInputConnectionImpl(10040): requestCursorAnchorInfo on inactive InputConnection
W/RemoteInputConnectionImpl(10040): getSurroundingText on inactive InputConnection
2
W/RemoteInputConnectionImpl(10040): requestCursorAnchorInfo on inactive InputConnection
W/RemoteInputConnectionImpl(10040): getExtractedText on inactive InputConnection
D/InsetsController(10040): show(ime(), fromIme=true)
I/ImeTracker(10040): com.example.myapp:5f56dc9d: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
I/ImeTracker(10040): com.example.myapp:7a73f231: onShown
W/WindowOnBackDispatcher(10040): sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@146993849 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@b916bec
I/ImeTracker(10040): com.example.myapp:7e61ee3f: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
I/ImeTracker(10040): com.example.myapp:4005a505: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
I/ImeTracker(10040): com.example.myapp:a6c9e7fa: onHidden
```

**Comment by Knightro63** [comment]
Hi @Mamena2020,

Thank you for reporting. Would not have found this otherwise. I will add this fix in the next update, but for you to have it working now you need to go to the peripherals.dart file and make the below changes.

```dart
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((t) {
      if (_clientWidth == null || _clientHeight == null) {
        RenderBox getBox = context.findRenderObject() as RenderBox;
        _clientWidth = getBox.size.width;
        _clientHeight = getBox.size.height;
        Offset temp = getBox.localToGlobal(Offset.zero);
        _offsetLeft = temp.dx;
        _offsetTop = temp.dy;
        
      }
      FocusScope.of(context).requestFocus(focusNode);
    });
  }
```

```dart
  @override
  Widget build(BuildContext context) {
    return KeyboardListener(
      focusNode: focusNode,
      onKeyEvent: (event){
        if(event is KeyDownEvent){
          _onKeyDownEvent(context, event.logicalKey);
        }
        else if(event is KeyUpEvent){
          _onKeyUpEvent(context, event.logicalKey);
        }
      },
      child:Listener(
        onPointerSignal: (pointerSignal) {
          if (pointerSignal is PointerScrollEvent) {
            _onWheel(context, pointerSignal);
          }
        },
        onPointerDown: (PointerDownEvent event) {
          _onPointerDown(context, event);
          FocusScope.of(context).requestFocus(focusNode);
        },
        onPointerMove: (PointerMoveEvent event) {
          _onPointerMove(context, event);
        },
        onPointerUp: (PointerUpEvent event) {
          _onPointerUp(context, event);
        },
        onPointerCancel: (PointerCancelEvent event) {
          _onPointerCancel(context, event);
        },
        onPointerHover: (PointerHoverEvent event){
          _onMouseMove(context, event);
        },
        child: widget.builder(context),
      )
    );
  }
```

This should fix the issue you are having.

**Comment by BjornJ04** [comment]
Hi @Knightro63,

I'm also having this issue. I tried your solution and now it works better, but sometimes the keyboard still does not open. I'm experiencing this issue on iOS and Android, both physical and simulator and both debug and release versions.

**Comment by Knightro63** [comment]
Hi @BjornJ04 ,

For this to work effectively you have to render the text field over the threeJs viewer and you need to add a focus node and make sure your focus node for that text field has priority. I will add an example later this week and post a link here.

**Comment by Mamena2020** [comment]
@Knightro63  thank you for your response, can't wait for next updates.

**Comment by BjornJ04** [comment]
Hi @Knightro63,

Just wanted to check in and see if the example you mentioned is available yet. I’m eager to implement it and would really appreciate any updates or guidance you can provide.

**Comment by Knightro63** [comment]
Hi @BjornJ04,

Below is an example of how I was able to get this to work as well as having the changes I suggested above.

```dart
import 'dart:async';
import 'package:example/src/statistics.dart';
import 'package:flutter/material.dart';
import 'package:three_js/three_js.dart' as three;
import 'package:three_js_helpers/three_js_helpers.dart';


class WebglLoaderGltf3 extends StatefulWidget {
  const WebglLoaderGltf3({super.key});

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<WebglLoaderGltf3> {
  static final _textKey = GlobalKey<FormState>();

  List<int> data = List.filled(60, 0, growable: true);
  late Timer timer;
  late three.ThreeJS threeJs;
  TextEditingController controller = TextEditingController();
  final FocusNode focusNode = FocusNode();

  @override
  void initState() {
    timer = Timer.periodic(const Duration(seconds: 1), (t){
      setState(() {
        data.removeAt(0);
        data.add(threeJs.clock.fps);
      });
    });
    threeJs = three.ThreeJS(
      onSetupComplete: (){setState(() {});},
      setup: setup,
      settings: three.Settings(
        clearAlpha: 0,
        clearColor: 0xffffff,
      ),
    );
    super.initState();
  }
  @override
  void dispose() {
    timer.cancel();
    controls.dispose();
    threeJs.dispose();
    three.loading.clear();

    focusNode.dispose();
    controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          threeJs.build(),
          Statistics(data: data),
          Container(
            margin: const EdgeInsets.fromLTRB(10, 0, 10, 0),
            width: MediaQuery.of(context).size.width,
            height: 240,
            alignment: Alignment.center,
            child: TextField(
              key: _textKey,
              keyboardType: TextInputType.multiline,
              autofocus: false,
              focusNode: focusNode,
              //textAlignVertical: TextAlignVertical.center,
              onTap: (){
                FocusScope.of(context).requestFocus(focusNode);
              },
              onChanged: (t){
                print(t);
              },
              onEditingComplete:(){
                print('did Complete');
              },
              controller: controller,
              style: Theme.of(context).primaryTextTheme.bodyMedium,
              decoration: InputDecoration(
                isDense: true,
                //labelText: label,
                filled: true,
                fillColor: Theme.of(context).splashColor,
                contentPadding: const EdgeInsets.fromLTRB(10.0, 10.0, 10.0, 0.0),
                border: const OutlineInputBorder(
                  borderRadius: BorderRadius.all(
                    Radius.circular(10.0),
                  ),
                  borderSide: BorderSide(
                      width: 0, 
                      style: BorderStyle.none,
                  ),
                ),
                hintStyle: Theme.of(context).primaryTextTheme.bodyMedium!.copyWith(color: Colors.grey),
                hintText: 'Type Text Here'
              ),
            )
          )
        ],
      ) 
    );
  }

  late three.OrbitControls controls;
  late three.AnimationMixer mixer;

  Future<void> setup() async {
    threeJs.scene = three.Scene();

    threeJs.camera = three.PerspectiveCamera(45, threeJs.width / threeJs.height, 1, 2200);
    threeJs.camera.position.setValues( 0,1,10);
    threeJs.camera.lookAt(threeJs.scene.position);

    controls = three.OrbitControls(threeJs.camera, threeJs.globalKey);

    final pointLight = three.PointLight(0xffffff, 0.8);
    pointLight.position.setValues(0, 0, 10);
    threeJs.scene.add(pointLight);

    three.RGBELoader rgbeLoader = three.RGBELoader(flipY: true);
    rgbeLoader.setPath('assets/textures/equirectangular/');
    final hdrTexture = await rgbeLoader.fromAsset('royal_esplanade_1k.hdr');
    hdrTexture?.mapping = three.EquirectangularReflectionMapping;
    
    threeJs.scene.background = hdrTexture;
    threeJs.scene.environment = hdrTexture;

    threeJs.scene.add( three.AmbientLight( 0xffffff ) );

    three.GLTFLoader loader = three.GLTFLoader().setPath('assets/models/gltf/');
    final result = await loader.fromAsset('Xbot.gltf');

    final object = result!.scene;
    object.scale.setValues(2, 2, 2);

    final skeleton = SkeletonHelper(object);
    skeleton.visible = true;
    threeJs.scene.add(skeleton);

    mixer = three.AnimationMixer(object);

    final clip = result.animations?[1];
    if (clip != null) {
      final action = mixer.clipAction(clip);
      action?.play();
    }

    threeJs.scene.add(object);
  
    threeJs.addAnimationEvent((dt){
      controls.update();
      mixer.update(dt);
    });
  }
}

```

**Comment by Knightro63** [comment]
Hi @BjornJ04,

Please update to the latest version of three_js: ^0.1.0. I believe I have fixed the issue causing this.

**Comment by Knightro63** [comment]
Hi @BjornJ04,

Has this been resolved for you. I believe this is fixed. I will close this soon.

**Comment by Mamena2020** [comment]
Finally it works at version `three_js: ^0.1.1`. Thanks to @Knightro63
